### PR TITLE
Fix for GCC lost in SDK v8.0 update

### PR DESCRIPTION
**Pull request by rosterloh**
This fix was previously in the library but was lost when porting over to new SDK

### CODE REVIEW

**Comment by 0xc0170** [comment]
where was this fixed, in mbed sources or in sources coming from nordic?

**Comment by rosterloh** [comment]
It was fixed in this library. The nrf_svc.h file had it in but was not in the Nordic sources

**Comment by 0xc0170** [comment]
As I understand, it should be reported to them

**Comment by rosterloh** [comment]
I just though I might submit it here as it was in before and no one who uses this library with mbed when they export to local compiler will be able to build.

**Comment by 0xc0170** [comment]
@rosterloh Yes, correct. My point was that we should report this type of bugs (along with fixing them locally) directly to the file owners. @rgrover will look at this PR

**Pull request merged**
