### PR TITLE
line 81, explicit cast to (event_header_t *), caused error in ds-5 

### PR DESCRIPTION
**Pull request by jslater8**

### CODE REVIEW

**Comment by rgrover** [comment]
Can you please discuss this change with me? As far as possible, we should avoid changing files inherited from the nordic SDK. Thanks.

**Comment by jslater8** [comment]
generates an error in ds-5 when compiling, but it should work anyway without an explicit cast if the error is ignored.

**Comment by rgrover** [comment]
can you switch to more permissive compiler options when compiling the files under nordic-sdk? thanks.

**Comment by rgrover** [comment]
feel free to reopen if you feel this should be addressed properly.

**Pull request closed without merging**
